### ISSUE TITLE
No groq/llama-3.2-90b-vision-preview support 

### ISSUE THREAD

**Issue by mkagit** [jakobdylanc/llmcord#66]
Tried to attach an image and prompt the groq/llama-3.2-90b-vision-preview but it is not working.

**Comment by jakobdylanc** [comment]
Can you share the error you're seeing?

**Comment by mkagit** [comment]
<html>
<body>

2024-11-05 13:31:41.760 | openai.BadRequestError: Error code: 400 - {'error': {'message': 'prompting with images is incompatible with system messages', 'type': 'invalid_request_error'}} |  
-- | -- | --
  |   | 2024-11-05 13:31:41.760 | raise self._make_status_error_from_response(err.response) from None |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1633, in _request |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self._request( |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1532, in request |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1838, in post |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self._post( |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1661, in create |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | async for curr_chunk in await openai_client.chat.completions.create(**kwargs): |  
  |   | 2024-11-05 13:31:41.760 | File "/app/llmcord.py", line 201, in on_message |  
  |   | 2024-11-05 13:31:41.760 | Traceback (most recent call last): |  
  |   | 2024-11-05 13:31:41.760 | 2024-11-05 16:31:41,755 ERROR: Error while generating response |  
  |   | 2024-11-05 13:31:41.754 | 2024-11-05 16:31:41,753 INFO: HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 400 Bad Request"


</body>
</html>

**Comment by mkagit** [comment]
```
2024-11-05 13:31:41.760 | openai.BadRequestError: Error code: 400 - {'error': {'message': 'prompting with images is incompatible with system messages', 'type': 'invalid_request_error'}} |  
-- | -- | --
  |   | 2024-11-05 13:31:41.760 | raise self._make_status_error_from_response(err.response) from None |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1633, in _request |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self._request( |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1532, in request |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/_base_client.py", line 1838, in post |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | return await self._post( |  
  |   | 2024-11-05 13:31:41.760 | File "/usr/local/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1661, in create |  
  |   | 2024-11-05 13:31:41.760 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |  
  |   | 2024-11-05 13:31:41.760 | async for curr_chunk in await openai_client.chat.completions.create(**kwargs): |  
  |   | 2024-11-05 13:31:41.760 | File "/app/llmcord.py", line 201, in on_message |  
  |   | 2024-11-05 13:31:41.760 | Traceback (most recent call last): |  
  |   | 2024-11-05 13:31:41.760 | 2024-11-05 16:31:41,755 ERROR: Error while generating response |  
  |   | 2024-11-05 13:31:41.754 | 2024-11-05 16:31:41,753 INFO: HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 400 Bad Request"

```

**Comment by jakobdylanc** [comment]
> prompting with images is incompatible with system messages

This is a weakness on OpenRouter's end.

In llmcord, you can disable the system prompt by simply leaving it empty in the config. This should fix your issue.

**Comment by mkagit** [comment]
It's working now, thanks!
