### ISSUE TITLE
Not able to @ the bot in a Forum

### ISSUE THREAD

**Issue by jczhang07** [jakobdylanc/llmcord#67]
Hello, @jakobdylanc, thanks for the llmcord. I have been playing with it in our Discord server.

I created two test channels (both non-private), one was a regular channel and the other was a Forum type channel.  I found I could mention the bot in the regular channel but not in the Forum channel.  In the later case, the bot just kept silent and gave no response. 

Do you know whether it is a llmcord issue or a my Discord setting issue?

Thanks!

**Comment by jakobdylanc** [comment]
Thanks for using llmcord!

I intentionally restricted llmcord to only work in certain channel types. This is defined by ALLOWED_CHANNEL_TYPES at the top of llmcord.py.

The reason I didn't include forum channels is because, for some reason, the discord.py library does not have a `fetch_message` method for forum channels. `fetch_message` is important for llmcord's reply-based functionality.

**Comment by jczhang07** [comment]
Oh, I see. Looking at https://discord.com/developers/docs/resources/channel#channel-object-channel-types, I tried to append `discord.ChannelType.guild_forum` in `ALLOWED_CHANNEL_TYPES` but it did not work. The Discord python module complained:  

> AttributeError: type object 'ChannelType' has no attribute 'guild_forum'

My goal is to forward emails to our mailing-list to a Discord channel and let the LLM bot to make a draft reply. I just feel a Forum channel with posts (title + message) is better suited to email threads.

**Comment by jakobdylanc** [comment]
The correct entry would be `discord.ChannelType.forum`, per discord.py's documentation:
https://discordpy.readthedocs.io/en/stable/api.html?highlight=channeltype#discord.ChannelType

If you experiment and find anything out, let me know. I'll do the same when I have time :)

**Comment by jczhang07** [comment]
I tried `discord.ChannelType.forum` and the llmcord.py ran fine. But I still could not mention the bot (`Llama`) in the Forum.  In the regular channel, I could do it, but with a limitation.  

I have a Discord webhook for the channel.  I posted a message via the webhook (`Email-forwarder`) and mentioned the bot.   But the bot did not respond.  However, I could manually mention the bot.  See the attachment.  Is it an issue of llmcord?


![Screenshot 2024-11-05 at 2 46 39 PM](https://github.com/user-attachments/assets/6a54a0fd-6507-47e5-9102-b5ffeb3b0b9c)

**Comment by jakobdylanc** [comment]
Yeah, llmcord does the following in its message filtering:

```python
if discord_client.user not in new_msg.mentions:
    return
```

I think that since your bot is just pasting the literal mention string, it doesn't count as a *proper* mention, so it won't show up in `mentions`.

You can fix this by making it look for the literal mention string instead:

```python
if discord_client.user.mention not in new_msg.content:
    return
```

This might be better, so I might push this change. For now you can try it yourself.

Just change this line:
https://github.com/jakobdylanc/llmcord/blob/1992a546e2ef013e615d1248cd05275ca515639b/llmcord.py#L76

To this:

```python
or (new_msg.channel.type != discord.ChannelType.private and discord_client.user.mention not in new_msg.content)
```

**Comment by jczhang07** [comment]
I made the change at line 76 but it did not work.  Actually, I did use a proper mention (vs a literal string) in the format of `<@AppId>`,  e.g.,`<@1295421604515287048>` in the message, that's why we could see `@Llama` in the picture.

**Comment by jakobdylanc** [comment]
Oh whoops, llmcord also filters out all bot messages. I overlooked this : )

I'm on mobile right now so can't link to the code easily. But you should be able to find the line that filters out bot messages. Just remove it.

**Comment by jakobdylanc** [comment]
It's line 77

**Comment by jczhang07** [comment]
Thanks. It works now!

**Comment by jakobdylanc** [comment]
How are you finding the functionality in forums? Like continuing conversations?

I imagine it might work OK most of the time. But if you restart the bot, and then continue a previous conversation, I think you will see issues (this is when `fetch_message` would be called).

**Comment by jczhang07** [comment]
With the diff, I was able to mention the bot in Forum.  I have not done extensive test with the Forum yet.  But I saw errors with DM (a chain of short/empty responses).  See the attachment. 
```diff
22c22
< ALLOWED_CHANNEL_TYPES = (discord.ChannelType.text, discord.ChannelType.public_thread, discord.ChannelType.private_thread, discord.ChannelType.private)
---
> ALLOWED_CHANNEL_TYPES = (discord.ChannelType.text, discord.ChannelType.public_thread, discord.ChannelType.private_thread, discord.ChannelType.private, discord.ChannelType.forum)
77d76
<         or new_msg.author.bot
```

![Screenshot 2024-11-07 at 3 38 16 PM](https://github.com/user-attachments/assets/22076265-e9b3-4fe5-9259-6a15277481a9)

**Comment by jakobdylanc** [comment]
Ah, I think that's because the bot is getting triggered by itself, since you removed the "new_msg.author.bot" check. You've opened a can of worms :)

**Comment by jakobdylanc** [comment]
I think instead of removing line 77, you should keep it, but change it to:

```python
or (new_msg.channel.type == discord.ChannelType.private and new_msg.author.bot)
```

**Comment by jczhang07** [comment]
The change fixed the DM issue.  Thanks!
