### ISSUE TITLE
AI forgets in DMs

### ISSUE THREAD

**Issue by Meeep1** [jakobdylanc/llmcord#69]
First in DMs the bot only remembers when they are replied to but forgets it if you don't reply

Second would it be possible for when your chatting with the bot in DMs or in threads you wouldn't have to reply for it to remember the conversation.

**Comment by jakobdylanc** [comment]
llmcord uses the reply-based chat system everywhere. Without it you would lose a significant amount of control. How would you start a new conversation? Or rewind the conversation to any point? Etc.

I don't plan on changing this. Hope it makes sense.

**Comment by mkagit** [comment]
Is there a way to config.yaml option to disable the DM feature if one needs? For example, if I want more control to keep all conversations in the channels and avoid people using it for DM personal use.

**Comment by jakobdylanc** [comment]
There isn't a specific setting to disable DMs. But you can use "allowed_channel_ids" to restrict the bot to certain channels, or use "allowed_role_ids" to restrict usage to certain guild roles. Both are effective ways to disable DMs.

**Comment by jczhang07** [comment]
> llmcord uses the reply-based chat system everywhere. Without it you would lose a significant amount of control. How would you start a new conversation? Or rewind the conversation to any point? Etc.
> 
> I don't plan on changing this. Hope it makes sense.

In DM, it is not easy to define the conversation context. But in a thread, it is very clear (the context is the whole thread).  I think it makes sense to do that in threads without using reply.

**Comment by jakobdylanc** [comment]
> I think it makes sense to do that in threads without using reply

I disagree, since threads can have multiple users.

What if a user wants to send a message in the thread without triggering the bot?

What if users start sending off-topic messages which pollutes your conversation with the bot?

Etc...

**Comment by jczhang07** [comment]
> > I think it makes sense to do that in threads without using reply
> 
> I disagree, since threads can have multiple users.
> 
> What if a user wants to send a message in the thread without triggering the bot?
> 
I don't know the mechanism.  Can we just leave the message as is, and then when someone types "@bot, what do you think?", the bot scans all messages in the thread up to now and gives a response?
> What if users start sending off-topic messages which pollutes your conversation with the bot?
That is users' problem. In our targeted use case (email threads), we don't have this concern. 
> 
> Etc...

**Comment by jakobdylanc** [comment]
> I don't know the mechanism. Can we just leave the message as is, and then when someone types "@bot, what do you think?", the bot scans all messages in the thread up to now and gives a response?

True, the bot could still only be triggered when you @ it. Why didn't I think of that?

> That is users' problem. In our targeted use case (email threads), we don't have this concern.

Regardless, reply chaining is the core functionality of llmcord. It allows for true asynchronicity, and gives the user maximum control over the conversation.

The alternative you're suggesting makes it so the user has to click 1 less button, but has no other strengths.

**Comment by mkagit** [comment]
> That is users' problem. In our targeted use case (email threads), we don't have this concern. 
> > 

IMHO Jacob is thinking about general uses not specific one.

**Comment by jakobdylanc** [comment]
I could maybe change DM behavior so that:

- when you send a message with no @, it automatically continues from the last message
- when you send a message with a @, it starts a new conversation

**Comment by jakobdylanc** [comment]
Done! This is a great improvement I think. Thanks for the discussion!
