### ISSUE TITLE
[Suggestion] placeholder response

### ISSUE THREAD

**Issue by Mohamed3nan** [jakobdylanc/llmcord#75]
I suggest implementing an immediate placeholder response such as:

"Bot is preparing..."

to be sent as soon as the bot receives a message. Once the API response is received, the placeholder message can then be edited or replaced with the actual response.

I tried implementing it with cursor help and it worked, but it required significant changes to the structure, and I figured you might not be on board with such a big refactor 😅.

What do you think?

**Comment by jakobdylanc** [comment]
Why would this be necessary?

It sends a typing indicator which is plenty I think: 

![image](https://github.com/user-attachments/assets/4fee0609-d879-479b-a3bc-5663e4d90ea4)

**Comment by Mohamed3nan** [comment]
because sometimes the response takes a lot of time and some times no response due to any error
and the most important when more than one talk to the bot the insta reply will prevent spam when people think that they are something wrong when it takes some time to get the api respond..

**Comment by jakobdylanc** [comment]
You raise some good points. There are always caveats though.

For example, the bot's response can be split into multiple messages if it's very long. Ideally these messages should be back-to-back for easy readability. If we send a placeholder response, and then the bot takes long to respond, and meanwhile more conversation is happening in the channel, now the subsequent messages will be separated from the first one. Not ideal.

Another idea is making the bot react to your message with a :hourglass: to let you know that it's processing. If the response is successful then the reaction is removed. If there's an error then it could be replaced with a :x:.

I hope that as LLMs continue to advance, slowness becomes less of a problem in general :)

**Comment by Mohamed3nan** [comment]
> For example, the bot's response will sometimes be split into multiple messages if it's very long. Ideally these messages should be back-to-back for easy readability. If we send a placeholder response, and then the bot takes long to respond, and meanwhile more conversation is happening in the channel, now the subsequent messages will be separated from the first one. Not ideal.
> 

This is the challenging part. Honestly, I tried many iterations with Cursor until it worked, but there are still some bugs with images sometimes.

here is how it looks..
![Animation](https://github.com/user-attachments/assets/e8ffbba1-b675-4b96-b9b3-ccc1f930a6bf)

**Comment by jakobdylanc** [comment]
Wow that's SLOW! Lol

**Comment by Mohamed3nan** [comment]
> Wow that's SLOW! Lol

Yeah because i use unofficial openai api lol :D
