### ISSUE TITLE
Error when pinging bot on Discord, will not respond.

### ISSUE THREAD

**Issue by TheBlueSavior** [jakobdylanc/llmcord#81]
```
2024-12-05 11:41:47,511 ERROR: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Blue\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Blue\Desktop\llmcord\llmcord.py", line 92, in on_message
    provider, model = cfg["model"].split("/", 1)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

I know very little about python besides it causing me headaches, but did I manage to set this up all the way to the bot being online, connected to discord, and the config set to use LM Studio. I followed the pinned thread in issues to ensure everything was up to date, I just downloaded all of this today. I've tried multiple models, nothing is working to get me past the error above. Any input would be greatly appreciated.

**Comment by jakobdylanc** [comment]
From the looks of it, you have `model` set incorrectly in the config. It should be in the format of `<provider name>/<model name>`. For LM Studio you can try `lmstudio/model` (I don't think the model name matters with LM Studio unless you have multiple models loaded).

**Comment by TheBlueSavior** [comment]
> From the looks of it, you have `model` set incorrectly in the config. It should be in the format of `<provider name>/<model name>`. For LM Studio it should be `lmstudio/model` (I don't think the model name matters with LM Studio unless you have >1 models loaded).

Bingo! Thanks a lot, must've missed the difference in how to reference it. And here I was just typing in the model's api identifier and nothing else. Thanks again!

**Comment by jakobdylanc** [comment]
Sweet, enjoy 🫡
